package com.syndic8.phytopolis;

import com.badlogic.gdx.Screen;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.math.Vector2;
import com.syndic8.phytopolis.assets.AssetDirectory;
import com.syndic8.phytopolis.util.FilmStrip;
import com.syndic8.phytopolis.util.ScreenListener;
import edu.cornell.gdiac.audio.AudioEngine;

public class LevelSelectMode implements Screen {
    /**
     * Whether or not this screen is active
     */
    private boolean active;
    /**
     * Reference to GameCanvas created by the root
     */
    private GameCanvas canvas;
    /**
     * Listener that will update the player mode when we are done
     */
    private ScreenListener listener;
    private FilmStrip background;
    private Texture lighting;
    private boolean ready;
    private final Rectangle bounds;
    private Music backgroundMusic;
    private AudioEngine audioEngine;


    public LevelSelectMode(){
        this.ready = false;
        this.bounds = new Rectangle(0, 0, 16, 9);
    }

    public void gatherAssets(AssetDirectory directory){
        background = new FilmStrip(directory.getEntry("lvlsel:background",
                Texture.class), 1, 4);
        lighting = directory.getEntry("lvlsel:lighting", Texture.class);
        backgroundMusic = directory.getEntry("newgrowth", Music.class);
        backgroundMusic.setLooping(true);
        backgroundMusic.play();
    }

    public void setCanvas(GameCanvas canvas) {
        this.canvas = canvas;
    }
    @Override
    public void show() {
        active = true;
        if (backgroundMusic != null) backgroundMusic.play();
    }

    @Override
    public void render(float delta) {
        if (active) {
            update(delta);
            draw();

            if (listener != null && ready) {
                listener.exitScreen(this, 0);
            }
        }
    }

    public void update(float delta){
        float mouseX = InputController.getInstance().getMouseX();
        float mouseY = InputController.getInstance().getMouseY();
        InputController.getInstance().readInput(bounds, Vector2.Zero.add(1, 1));
        //TODO remove this
        if(InputController.getInstance().didSecondary()) ready = true;
        //TODO Check if player clicked on a pot, listener.exitScreen if did
    }

    public void draw(){
        canvas.clear();
        canvas.begin();
        canvas.setBlendState(GameCanvas.BlendState.ADDITIVE);
        canvas.draw(background,
                Color.WHITE,
                0,
                0,
                canvas.getWidth(),
                canvas.getHeight());
        canvas.draw(lighting,
                Color.WHITE,
                0,
                0,
                canvas.getWidth(),
                canvas.getHeight());
        canvas.setBlendState(GameCanvas.BlendState.NO_PREMULT);
        canvas.end();
    }

    public void setScreenListener(ScreenListener listener) {
        this.listener = listener;
    }

    @Override
    public void resize(int i, int i1) {
        //Autogenerated, can ignore
    }

    @Override
    public void pause() {
        //Autogenerated, can ignore
    }

    @Override
    public void resume() {
        //Autogenerated, can ignore
    }

    @Override
    public void hide() {
        active = false;
        backgroundMusic.stop();
    }

    @Override
    public void dispose() {
        backgroundMusic.dispose();
    }
}
