package com.syndic8.phytopolis;

import com.badlogic.gdx.Screen;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.math.Rectangle;
import com.badlogic.gdx.math.Vector2;
import com.syndic8.phytopolis.assets.AssetDirectory;
import com.syndic8.phytopolis.util.FadingScreen;
import com.syndic8.phytopolis.util.ScreenListener;
import edu.cornell.gdiac.audio.AudioEngine;

public class VictoryMode extends FadingScreen implements Screen {

    private final Rectangle bounds;
    /**
     * Whether or not this screen is active
     */
    private boolean active;
    /**
     * Reference to GameCanvas created by the root
     */
    private GameCanvas canvas;
    /**
     * Listener that will update the player mode when we are done
     */
    private ScreenListener listener;
    private Texture background;
    private boolean ready;
    private Music backgroundMusic;
    private AudioEngine audioEngine;
    private Texture rs;

    public VictoryMode() {
        this.ready = false;
        this.bounds = new Rectangle(0, 0, 16, 9);
    }

    public void gatherAssets(AssetDirectory directory) {
        background = directory.getEntry("victory:background", Texture.class);
        //        backgroundMusic = directory.getEntry("newgrowth", Music.class);
        //        backgroundMusic.setLooping(true);
        //        backgroundMusic.play();
    }

    public void setBackgroundMusic(Music m) {
        backgroundMusic = m;
    }

    public void setCanvas(GameCanvas canvas) {
        this.canvas = canvas;
    }

    @Override
    public void show() {
        active = true;
        fadeIn(0.5f);
        //        if (backgroundMusic != null) backgroundMusic.play();
    }

    @Override
    public void render(float delta) {
        if (active) {
            update(delta);
            draw();

            if (listener != null && ready && isFadeDone()) {
                listener.exitScreen(this, 0);
            }
        }
    }

    public void update(float delta) {
        super.update(delta);
        InputController.getInstance().readInput(bounds, Vector2.Zero.add(1, 1));
        if (InputController.getInstance().didSecondary()) {
            ready = true;
            fadeOut(0.5f);
        }
    }

    public void draw() {
        canvas.clear();
        canvas.begin();
        canvas.draw(background,
                    Color.WHITE,
                    0,
                    0,
                    canvas.getWidth(),
                    canvas.getHeight());
        canvas.end();
        super.draw(canvas);
    }

    @Override
    public void resize(int i, int i1) {
        //Autogenerated, can ignore
    }

    @Override
    public void pause() {
        //Autogenerated, can ignore
    }

    @Override
    public void resume() {
        //Autogenerated, can ignore
    }

    @Override
    public void hide() {
        active = false;
        //        backgroundMusic.stop();
    }

    @Override
    public void dispose() {
        //        backgroundMusic.dispose();
    }

    public void reset() {
        ready = false;
    }

    public void setScreenListener(ScreenListener listener) {
        this.listener = listener;
    }

}
